development:
  strategy: oauth
  oauth_consumer_key: "5ap9MtE89d7niMshV7f5Q"
  oauth_consumer_secret: "RQWND33kn3KgRLUruiQQHs0lwwSzMaLkg1CiNigypmg"
  base_url: "http://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
test:
  strategy: oauth
  oauth_consumer_key: "5ap9MtE89d7niMshV7f5Q"
  oauth_consumer_secret: "RQWND33kn3KgRLUruiQQHs0lwwSzMaLkg1CiNigypmg"
  authorize_path: "/oauth/authenticate"  
  base_url: "http://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
production:
  strategy: oauth
  oauth_consumer_key: "5ap9MtE89d7niMshV7f5Q"
  oauth_consumer_secret: "RQWND33kn3KgRLUruiQQHs0lwwSzMaLkg1CiNigypmg"
  authorize_path: "/oauth/authenticate"  
  base_url: "http://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
